web/protected/modules/userGroups/controllers/UserController.php
<?php

class UserController extends Controller {

    public $layout = '//layouts/main';

    /**
     * @var mixed tooltip for the permission menagement $fecha_ nombre passRequest
     */
    /* public static $_permissionControl = array(
      'write'=>'can invite other users.',
      'admin'=>'can edit other users, ban them and approve their registrations.',
      ); */
    //Para que no aparezca en el admin (root) de userGroups
    const TRAZA = "INSERT INTO auditoria.traza (username, fecha_hora, ip_maquina, tipo_transaccion, modulo) VALUES (:username, :fecha_hora, :ip_maquina, :tipo_transaccion, :modulo);";

    public static $_permissionControl = false;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'userGroupsAccessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // just guest can perform 'activate', 'login' and 'passRequest' actions
                'actions' => array('activate', 'login', 'passRequest'),
                'ajax' => false,
                'users' => array('?'),
            ),
            array('allow', // just guest can perform 'activate', 'login' and 'passRequest' actions
                'actions' => array('obtenerDatosPersona','registerNewUser'),
                'ajax' => true,
                'users' => array('?'),
            ),
            array('allow', // captchas can be loaded just by guests
                'actions' => array('captcha'),
                'expression' => 'UserGroupsConfiguration::findRule("registration")',
                'users' => array('?'),
            ),
            array('allow', // just guest can perform registration actions and just if it is enabled
                'actions' => array('register'),
                'ajax' => false,
                'expression' => 'UserGroupsConfiguration::findRule("registration")',
                'users' => array('?'),
            ),
            array('allow', // actions users can access while in recovery mode
                'actions' => array('recovery', 'logout'),
                'users' => array('#'),
            ),
            array('allow', // allow authenticated user to perform 'logout' actions
                'actions' => array('logout'),
                'users' => array('@'),
            ),
            array('allow', // allow logged user to access the userlist page if the have admin rights on users or if the list is public
                'actions' => array('index'),
                'expression' => 'UserGroupsConfiguration::findRule("public_user_list") || Yii::app()->user->pbac("userGroups.user.admin")',
                'users' => array('@'),
            ),
            array('allow', // allow guest to view users profiles according to the configuration
                'actions' => array('view'),
                'expression' => 'UserGroupsConfiguration::findRule("public_profiles")',
                'pbac' => array('write'),
            ),
            array('allow', // allow logged user to view other users profiles according to the configuration and always their own
                'actions' => array('view'),
                'expression' => 'strtolower(Yii::app()->user->name) === (isset($_GET["u"]) ? strtolower($_GET["u"]) : strtolower(Yii::app()->user->name))',
                'pbac' => array('write'),
            ),
            array('allow', // allow user with user admin permission to view every profile, approve, ban and invite users
                'actions' => array('invite'),
                'pbac' => array('write'),
            ),
            array('allow', // allow user with user admin permission to view every profile, approve, ban and invite users
                'actions' => array('view', 'approve', 'ban', 'invite'),
                'pbac' => array('admin', 'admin.admin'),
            ),
            array('allow', // allow a user tu open an update view just on their own accounts
                'actions' => array('update'),
                'expression' => '$_GET["id"] == Yii::app()->user->id',
                'ajax' => true,
            ),
            array('allow', // allow user with admin permission to perform any action
                'pbac' => array('admin', 'admin.admin'),
                'ajax' => true,
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * override of the actions method to implement captcha
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
        );
    }

    /**
     * Lists all users.
     */
    public function actionIndex() {
        $model = new UserGroupsUser('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['UserGroupsUser']))
            $model->attributes = $_GET['UserGroupsUser'];

        if (Yii::app()->request->isAjaxRequest)
            $this->renderPartial('index', array('model' => $model,), false, true);
        else
            $this->render('index', array('model' => $model,), false, true);
    }

    /**
     * render a user profile
     */
    public function actionView() {
        // load the user profile according to the request
        if (isset($_GET['u'])) {
            // look for the right user criteria to use according to the viewer permissions
            if (Yii::app()->user->pbac(array('user.admin', 'admin.admin')))
                $criteria = array('username' => $_GET['u']);
            else
                $criteria = array('username' => $_GET['u'], 'status' => UserGroupsUser::ACTIVE);
            // load the profile
            $model = UserGroupsUser::model()->findByAttributes($criteria);
            if ($model === null || ($model->relUserGroupsGroup->level > Yii::app()->user->level && !UserGroupsConfiguration::findRule('public_profiles')))
                throw new CHttpException(404, Yii::t('userGroupsModule.general', 'The requested page does not exist.'));
        } else
            $model = $this->loadModel(Yii::app()->user->id);

        // load the profile extensions
        $profiles = array();
        $profile_list = Yii::app()->controller->module->profile;


        foreach ($profile_list as $p) {
            // check if the profile data exist on the current user, otherwise
            // create an instance of the profile extension
            $relation = "rel$p";

            if (!$model->$relation instanceof CActiveRecord)
                $p_instance = new $p;
            else
                $p_instance = $model->$relation;

            // check if the profile extension is supporting profile views
            $views = $p_instance->profileViews();
            if (isset($views[UserGroupsUser::VIEW])) {
                $profiles[] = array('view' => $views[UserGroupsUser::VIEW], 'model' => $p_instance);
            }
        }


        if (Yii::app()->request->isAjaxRequest || isset($_GET['_isAjax']))
            $this->renderPartial('view', array('model' => $model, 'profiles' => $profiles), false, true);
        else
            $this->render('view', array('model' => $model, 'profiles' => $profiles));
    }

    /**
     * user registration
     */
    public function actionRegister() {
        $model = new UserGroupsUser('registration');

        // set the profile extension array
        $profiles = array();
        $profile_list = Yii::app()->controller->module->profile;

        foreach ($profile_list as $p) {
            // create an instance of the profile extension
            $p_instance = new $p('registration');
            // check if the profile extension is supporting registration
            $views = $p_instance->profileViews();
            if (isset($views[UserGroupsUser::REGISTRATION])) {
                $profiles[] = array('view' => $views[UserGroupsUser::REGISTRATION], 'model' => $p_instance);
            }
        }

        if (isset($_POST['UserGroupsUser'])) {
            $model->attributes = $_POST['UserGroupsUser'];
            // set validation for additional fields
            foreach ($profiles as &$p) {

                if (isset($_POST[get_class($p['model'])]))
                    $p['model']->attributes = $_POST[get_class($p['model'])];

                if (!$p['model']->validate())
                    $error = true;
            }
            if ($model->validate() && !isset($error)) {
                if ($model->save()) {
                    // save the related profile extensions
                    foreach ($profiles as $p) {
                        $p['model']->ug_id = $model->id;
                        $p['model']->save();
                    }
                    $this->redirect(Yii::app()->baseUrl . '/userGroups');
                }
            }
        }

        $this->render('register', array(
            'model' => $model,
            'profiles' => $profiles,
        ));
    }

    /**
     * user invite form
     */
    public function actionInvite() {
        $model = new UserGroupsUser('invitation');

        $this->performAjaxValidation($model);

        if (isset($_POST['UserGroupsUser'])) {
            $model->attributes = $_POST['UserGroupsUser'];
            if ($model->validate()) {
                if ($model->save()) {
                    $mail = new UGMail($model, UGMail::INVITATION);
                    $mail->send();
                } else
                    Yii::app()->user->setFlash('user', Yii::t('userGroupsModule.general', 'An Error Occurred. Please try later.'));

web/protected/modules/userGroups/views/admin/accessList.php
<?php $name = (int) $what === UserGroupsAccess::USER ? $data->username : $data->groupname; // assign to name it's value passw    ?>
<h3> 
    <?php
    if ((int) $what === UserGroupsAccess::USER) {
        if ($id === 'new')
            echo Yii::t('userGroupsModule.admin', 'New User: Data and Access Permissions');
        else
            echo Yii::t('userGroupsModule.admin', 'User {username}: Data and Access Permissions', array('{username}' => ucfirst($name)));
    } else {
        if ($id === 'new')
            echo Yii::t('userGroupsModule.admin', 'New Group: Data and Access Permissions');
        else
            echo Yii::t('userGroupsModule.admin', 'Group {groupname}: Data and Access Permissions', array('{groupname}' => ucfirst($name)));
    }
    ?>
</h3>
<?php
$form = $this->beginWidget('CActiveForm', array(
    'id' => 'user-groups-access-form-' . $what,
    'enableAjaxValidation' => false,
    'action' => Yii::app()->baseUrl . '/userGroups/admin',
        ));
?>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'ajaxUpdate' => false,
    'enableSorting' => false,
    'summaryText' => false,
    'id' => 'rule-list',
    'selectableRows' => 0,
    'columns' => array(
        array(
            'name' => 'Module',
        ),
        array(
            'name' => 'Controller',
        ),
        array(
            'name' => 'Read',
            'type' => 'raw',
        ),
        array(
            'name' => 'Write',
            'type' => 'raw',
        ),
        array(
            'name' => 'Admin',
            'type' => 'raw',
        ),
    ),
));
?>
<?php if (Yii::app()->user->pbac('userGroups.admin.admin')) { ?>
    <div class="row">
        <table>
            <tr>
                <?php
                if ((int) $what === UserGroupsAccess::GROUP):
                    ?>
                    <td><?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Group Level'), 'UserGroupsAccess_' . $what . '_level', array('class' => 'inline')) . CHtml::dropDownList('UserGroupsAccess[' . $what . '][level]', $data->level, array_reverse(range(0, Yii::app()->user->level - 1), true)); ?></td>
                    <td><?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Home'), 'UserGroupsAccess_' . $what . '_home', array('class' => 'inline')) . CHtml::dropDownList('UserGroupsAccess[' . $what . '][home]', $data->home, UserGroupsAccess::homeList()); ?></td>

                <tr>

                    <td><?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Group Name'), 'UserGroupsAccess_' . $what . '_groupname', array('class' => 'inline')); ?>
                        <?php echo CHtml::textField('UserGroupsAccess[' . $what . '][groupname]', $name); ?></td>
                <?php
                endif;
                ?>
            </tr>

        </table>
        <table>


            <?php if ((int) $what === UserGroupsAccess::USER) { ?>
                <tr>



                    <td>
        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Usuario'), 'UserGroupsAccess_' . $what . '_username', array('class' => 'inline')); ?>
                    </td>

                    <td>
        <?php echo CHtml::textField('UserGroupsAccess[' . $what . '][username]', $name); ?>

                    </td>








                    <td colspan="2">

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Group'), 'UserGroupsAccess_' . $what . '_group_id', array('class' => 'inline')) . CHtml::dropDownList('UserGroupsAccess[' . $what . '][group_id]', $data->group_id, UserGroupsGroup::groupList()); ?>

                        <?php
                        $home_lists = UserGroupsAccess::homeList();
                        array_unshift($home_lists, Yii::t('userGroupsModule.admin', 'Group Home: {home}', array('{home}' => $data->group_home)));
                        ?>

                    </td>

                </tr>

                <tr>



                    <td>

        <?php
        echo CHtml::label(Yii::t('userGroupsModule.general', 'Home'), 'UserGroupsAccess_' . $what . '_home', array('class' => 'inline'));
        ?>


                    </td>

                    <td>
        <?php echo CHtml::dropDownList('UserGroupsAccess[' . $what . '][home]', $data->home, $home_lists); ?>
                    </td>




                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Nombres'), 'UserGroupsAccess_' . $what . '_nombre', array('class' => 'inline')); ?>


                    </td>

                    <td>

        <?php
        echo CHtml::textField('UserGroupsAccess[' . $what . '][nombre]', $data->nombre);
        ?>
                    </td>

                </tr>



                <tr>

                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Apellidos'), 'UserGroupsAccess_' . $what . '_apellido', array('class' => 'inline')); ?>


                    </td>

                    <td>

        <?php
        echo CHtml::textField('UserGroupsAccess[' . $what . '][apellido]', $data->apellido);
        ?>
                    </td>

                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Cedula'), 'UserGroupsAccess_' . $what . '_cedula', array('class' => 'inline')); ?>


                    </td>

                    <td>

        <?php
        echo CHtml::textField('UserGroupsAccess[' . $what . '][cedula]', $data->cedula);
        ?>
                    </td>



                </tr>



                <tr>



                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Telefono'), 'UserGroupsAccess_' . $what . '_telefono', array('class' => 'inline')); ?>



                    </td>

                    <td>
        <?php
        echo CHtml::textField('UserGroupsAccess[' . $what . '][telefono]', $data->telefono);
        ?>
                    </td>




                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Email'), 'UserGroupsAccess_' . $what . '_email', array('class' => 'inline')); ?>


                    </td>

                    <td>
        <?php echo CHtml::textField('UserGroupsAccess[' . $what . '][email]', $data->email); ?>
                    </td>




                </tr>

                <tr>

                    <td>

        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Estado'), 'UserGroupsAccess_' . $what . '_estado_id', array('class' => 'inline')); ?>


                    </td>

                    <td>

        <?php
        $estado = new Estado();
        $estado_filtro = new CDbCriteria;
        $estado_filtro->order = 'nombre ASC';

        echo CHtml::dropDownList('UserGroupsAccess[' . $what . '][estado_id]', $data->estado_id, CHtml::listData(Estado::model()->findAll($estado_filtro), 'id', 'nombre'), array('prompt' => 'Seleccione...'));
        ?>  



                        <?php //echo CHtml::textField('UserGroupsAccess['.$what.'][estado_id]', $data->estado_id); ?>
                    </td>

                    <td>
                        <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Direccion'), 'UserGroupsAccess_' . $what . '_direccion', array('class' => 'inline')); ?>
                    </td>

                    <td>

        <?php echo CHtml::textArea('UserGroupsAccess[' . $what . '][direccion]', $data->direccion); ?>

                    </td>



                </tr>







        <?php
    }
    ?>


        </table>
    </div>
            <?php if ($id === 'new' && (int) $what === UserGroupsAccess::USER) { ?>
        <div class="row">
                <?php echo CHtml::label(Yii::t('userGroupsModule.general', 'Password'), 'UserGroupsAccess_' . $what . '_password', array('class' => 'inline')); ?>
        <?php echo CHtml::textField('UserGroupsAccess[' . $what . '][password]', $data->password); ?>
        </div>

    <?php }
    ?>
    <?php } ?>

<div class="row buttons left-flotted">
<?php echo CHtml::hiddenField('UserGroupsAccess[what]', $what); ?>
<?php echo CHtml::hiddenField('UserGroupsAccess[id]', $id); ?>
<?php echo CHtml::hiddenField('UserGroupsAccess[displayname]', ucfirst($name)); ?>
<?php echo CHtml::submitButton(Yii::t('userGroupsModule.general', 'Save')); ?>
</div>
<?php $this->endWidget(); ?>
<?php if ($id !== 'new' && Yii::app()->user->pbac('userGroups.admin.admin')): ?>

    <!--- aqui es doden hace el link para mostrar los datos usuario-->
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'user-groups-delete-form-' . $what,
        'enableAjaxValidation' => false,
        'action' => Yii::app()->baseUrl . '/userGroups/admin',
    ));
    ?>


    <div class="row buttons right-flotted">




    <?php echo CHtml::hiddenField('UserGroupsAccess[what]', $what); ?>
    <?php echo CHtml::hiddenField('UserGroupsAccess[id]', $id); ?>
    <?php echo CHtml::hiddenField('UserGroupsAccess[displayname]', ucfirst($name)); ?>
    <?php echo CHtml::hiddenField('UserGroupsAccess[delete]', 'yes'); ?>
    <?php
    if ((int) $what === UserGroupsAccess::USER)
        $confirm_message = Yii::t('userGroupsModule.admin', 'Do you really want to delete the user {user}?', array('{user}' => ucfirst($name)));
    else {
        $confirm_message = Yii::t('userGroupsModule.admin', 'Do you really want to delete the group {group}?', array('{group}' => ucfirst($name)));
        $confirm_message .= '\n' . Yii::t('userGroupsModule.admin', 'Remember if you delete a Group you\'ll delete all the users that belongs to it.');
    }
    ?>
        <?php echo CHtml::submitButton(Yii::t('userGroupsModule.general', 'Delete'), array('onclick' => 'js: if(confirm("' . $confirm_message . '")) {return true;}else{return false;}')); ?>
    </div>
        <?php $this->endWidget(); ?>
    <?php endif; ?>

web/protected/modules/userGroups/views/admin/configurations.php
<h1 class="closed" onclick="$(this).toggleClass('opened').nextAll('.hidden-pannell').first().slideToggle();"><?php echo Yii::t('userGroupsModule.admin', 'Main Configurations'); ?></h1>
<?php if(Yii::app()->user->hasFlash('configuration')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('configuration'); ?>
    </div>
<?php endif; ?>
<div class="hidden-pannell">
	<?php 
	if (Yii::app()->user->pbac('admin.admin')) {
		$form=$this->beginWidget('CActiveForm', array(
			'id'=>'user-groups-admin-form',
			'enableAjaxValidation'=>false,
		));
	}
	?>
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$confDataProvider,
		'id'=>'configuration-list',
		'enableSorting'=>false,
		'summaryText'=>false,
		'selectableRows'=>0,
		'columns'=>array(
			'rule',
			array(
				'name'=>'render',
				'type'=>'raw',
			),
			array(
				'name'=>'description',
				'type'=>'raw',
			), 
		),
	)); ?>
	<?php if (Yii::app()->user->pbac('admin.admin')): ?>
	<div class="row buttons">
		<?php echo CHtml::submitButton('Save'); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php endif; ?>
</div>

web/protected/modules/userGroups/views/admin/crons.php
<h1 class="closed" onclick="$(this).toggleClass('opened').next('.hidden-pannell').slideToggle();"><?php echo Yii::t('userGroupsModule.admin', 'Cron Jobs'); ?></h1>
<?php if(Yii::app()->user->hasFlash('crons')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('crons'); ?>
    </div>
<?php endif; ?>
<div class="hidden-pannell">
	<?php 
	if (Yii::app()->user->pbac('userGroups.admin.admin'))
		$form=$this->beginWidget('CActiveForm', array(
			'id'=>'user-groups-cron-form',
			'enableAjaxValidation'=>false,
		)); 
	?>
	<?php
	// load the cronjobs
	UGCron::init();
	UGCron::add(new UGCJGarbageCollection);
	UGCron::add(new UGCJUnban);
	foreach (Yii::app()->controller->module->crons as $c) {
		UGCron::add(new $c);
	} 
	?>
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$cronDataProvider,
		'id'=>'configuration-list',
		'enableSorting'=>false,
		'summaryText'=>false,
		'selectableRows'=>0,
		'columns'=>array(
			'name',
			array(
				'name'=>'lapse',
				'value'=> Yii::app()->user->pbac('userGroups.admin.admin') ? 'CHtml::textField("UserGroupsCron[$data->id]", $data->lapse, array("class" => "lapse"))' : '$data->lapse',
				'type'=>'raw',
			),
			array(
				'name'=>'last_occurrence',
				// TODO when stop supporting php 5.2 use strstr
				'value'=>'substr($data->last_occurrence,0,strpos($data->last_occurrence," "))',
			),
			array(
				'name'=>'status',
				'value'=>'UGCron::getStatus($data->name, true, true)',
				'type'=>'raw',
			), 
			array(
				'name'=>'description',
				'value'=>'UGCron::getDescriptions($data->name, true);',
			),
		),
	)); ?>
	<?php if (Yii::app()->user->pbac('userGroups.admin.admin')): ?>
	<div class="inline buttons">
		<?php echo CHtml::submitButton(Yii::t('userGroupsModule.general','Save')); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'user-groups-cron-delete-form-',
		'enableAjaxValidation'=>false,
		'action'=>'/userGroups/admin',
	)); ?>
	<div class="inline buttons">
		<?php echo CHtml::hiddenField('UserGroupsCronRemove[remove]', 'yes'); ?>
		<?php echo CHtml::submitButton(Yii::t('userGroupsModule.admin','Remove not installed CronJobs'), array('onclick' => 'js: if(confirm("'. Yii::t('userGroupsModule.admin', 'Do you really want to remove those CronJobs?').'")) {return true;}else{return false;}')); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php endif; ?>
</div>

web/protected/modules/userGroups/views/admin/documentation.php
<h2>Pagina de inicio del Sistema... Falta diseño</h2>

web/protected/modules/userGroups/views/admin/groups.php
<h1><?php echo Yii::t('userGroupsModule.general', 'Groups'); ?></h1>
<?php if(Yii::app()->user->hasFlash('group')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('group'); ?>
    </div>
<?php endif; ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$groupModel->search(),
	'id'=>'user-groups-group-grid',
	'enableSorting'=>false,
	'filter'=>$groupModel,
	'summaryText'=>false,
	'selectionChanged'=> 'function(id) { getPermission("'.Yii::app()->baseUrl.'", "'.UserGroupsAccess::GROUP.'", $.fn.yiiGridView.getSelection(id))}',
	'columns'=>array(
		'groupname',
		'level',
	),
)); ?>
<?php
if (Yii::app()->user->pbac('userGroups.admin.admin'))
	echo CHtml::ajaxLink(Yii::t('userGroupsModule.admin', 'add group'), 
	Yii::app()->createUrl('/userGroups/admin/accessList', array('what'=>UserGroupsAccess::GROUP, 'id'=>'new')), 
	array('success'=>'js: function(data){ $("#group-detail").slideUp("slow", function(){ $("#group-detail").html(data).slideDown();}); }'),
	array('id'=>'new-group-'.time()));
?>
<div id="group-detail" style="display:none;"></div>

web/protected/modules/userGroups/views/admin/menu.php
<?php

$userGroupsMenu = array();

if ($mode === 'profile') {
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','My Profile'), 'url'=>array('/userGroups'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
	if (isset($username))
		$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','{username}\'s Profile',array('{username}'=>$username)), 'url'=>array('/userGroups?u='.$username), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
} else if ($mode === 'edit')
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Edit Profile'), 'url'=>array('user/update', 'id'=>Yii::app()->user->id), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
else if ($mode === 'admin') {
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','My Profile'), 'url'=>array('/userGroups'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Edit {username}\'s Profile', array('{username}'=>$username)), 'url'=>array('user/update', 'id'=>$id), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
}

//$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Invite User'), 'url'=>array('user/invite'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('user.admin', 'admin.admin')), 'active' => isset($invite));
$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','User List'), 'url'=>array('user/index'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('user.admin', 'admin.admin'), 'public_user_list', 'OR'), 'active' => isset($list));
$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.admin','Root Tools'), 'url'=>array('admin/'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('admin.write', 'admin.admin')), 'active' => isset($root));
//$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.admin','Documentation'), 'url'=>array('admin/documentation'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac('admin.read'), 'active' => isset($documentation));

$this->widget('zii.widgets.CMenu', array(
	'items'=>$userGroupsMenu,
	'htmlOptions'=>array('class'=>'userGroupsMenu'),
	'lastItemCssClass' => 'last',
));